version: '3.8'

services:
  # Core MCP Server
  lifearchivist-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./vault:/app/vault
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - LIFEARCH_DATABASE_URL=sqlite:///app/data/lifearch.db
      - LIFEARCH_QDRANT_URL=http://qdrant:6333
      - LIFEARCH_REDIS_URL=redis://redis:6379
      - LIFEARCH_OLLAMA_URL=http://ollama:11434
      - LIFEARCH_VAULT_PATH=/app/vault
      - LIFEARCH_LOCAL_ONLY=true
    depends_on:
      - qdrant
      - redis
      - ollama
    networks:
      - lifearchivist
    restart: unless-stopped

  # Vector Database
  qdrant:
    image: qdrant/qdrant:v1.12.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - lifearchivist
    restart: unless-stopped

  # Redis for Task Queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - lifearchivist
    restart: unless-stopped

  # Local LLM with Ollama
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1  # Limit parallel requests
      - OLLAMA_MAX_LOADED_MODELS=1  # Only keep 1 model in memory
      - OLLAMA_KEEP_ALIVE=5m
    networks:
      - lifearchivist
    deploy:
      resources:
        limits:
          memory: 8G  # Adjust based on your system
        reservations:
          memory: 4G
    restart: unless-stopped
    # GPU support disabled for Mac compatibility
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  # Background Worker for Document Processing
  lifearchivist-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m arq lifearchivist.workers.settings.WorkerSettings
    volumes:
      - ./vault:/app/vault
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - LIFEARCH_DATABASE_URL=sqlite:///app/data/lifearch.db
      - LIFEARCH_QDRANT_URL=http://qdrant:6333
      - LIFEARCH_REDIS_URL=redis://redis:6379
      - LIFEARCH_OLLAMA_URL=http://ollama:11434
      - LIFEARCH_VAULT_PATH=/app/vault
    depends_on:
      - redis
      - qdrant
      - ollama
    networks:
      - lifearchivist
    restart: unless-stopped

  # Optional: Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - lifearchivist-server
    networks:
      - lifearchivist
    restart: unless-stopped
    profiles:
      - production

volumes:
  qdrant_data:
    driver: local
  redis_data:
    driver: local
  ollama_data:
    driver: local

networks:
  lifearchivist:
    driver: bridge