version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lifearchivist
      - POSTGRES_USER=lifearchivist
      - POSTGRES_PASSWORD=lifearchivist_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./lifearchivist/storage/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lifearchivist"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - lifearchivist-dev

  qdrant:
    image: qdrant/qdrant:v1.12.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - lifearchivist-dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - lifearchivist-dev

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - lifearchivist-dev
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

volumes:
  postgres_data:
  qdrant_data:
  redis_data:
  ollama_data:

networks:
  lifearchivist-dev:
    driver: bridge