version: '3.8'

services:
  # Core MCP Server
  lifearchivist-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./vault:/app/vault
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - LIFEARCH_DATABASE_URL=postgresql://lifearchivist:lifearchivist_dev@postgres:5432/lifearchivist
      - LIFEARCH_QDRANT_URL=http://qdrant:6333
      - LIFEARCH_REDIS_URL=redis://redis:6379
      - LIFEARCH_OLLAMA_URL=http://ollama:11434
      - LIFEARCH_VAULT_PATH=/app/vault
      - LIFEARCH_LOCAL_ONLY=true
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
      redis:
        condition: service_started
      ollama:
        condition: service_started
    networks:
      - lifearchivist
    restart: unless-stopped

  # Vector Database
  qdrant:
    image: qdrant/qdrant:v1.12.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - lifearchivist
    restart: unless-stopped

  # Redis for Task Queue and Caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - lifearchivist
    restart: unless-stopped

  # PostgreSQL for Relational Data (Conversations, Users, etc.)
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lifearchivist
      - POSTGRES_USER=lifearchivist
      - POSTGRES_PASSWORD=lifearchivist_dev
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./lifearchivist/storage/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    command: 
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=1GB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=2621kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lifearchivist"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lifearchivist
    restart: unless-stopped

  # Local LLM with Ollama
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1  # Limit parallel requests
      - OLLAMA_MAX_LOADED_MODELS=1  # Only keep 1 model in memory
      - OLLAMA_KEEP_ALIVE=24h  # Keep model loaded for 24 hours
    networks:
      - lifearchivist
    deploy:
      resources:
        limits:
          memory: 8G  # Adjust based on your system
        reservations:
          memory: 4G
    restart: unless-stopped
    # GPU support disabled for Mac compatibility
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  # Background Worker for Document Processing
  lifearchivist-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m arq lifearchivist.workers.settings.WorkerSettings
    volumes:
      - ./vault:/app/vault
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - LIFEARCH_DATABASE_URL=postgresql://lifearchivist:lifearchivist_dev@postgres:5432/lifearchivist
      - LIFEARCH_QDRANT_URL=http://qdrant:6333
      - LIFEARCH_REDIS_URL=redis://redis:6379
      - LIFEARCH_OLLAMA_URL=http://ollama:11434
      - LIFEARCH_VAULT_PATH=/app/vault
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      qdrant:
        condition: service_started
      ollama:
        condition: service_started
    networks:
      - lifearchivist
    restart: unless-stopped

  # Optional: Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - lifearchivist-server
    networks:
      - lifearchivist
    restart: unless-stopped
    profiles:
      - production

volumes:
  qdrant_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local
  ollama_data:
    driver: local

networks:
  lifearchivist:
    driver: bridge