"""
Constants for WebSocket endpoints.
"""

MIN_SESSION_ID_LENGTH = 3

MESSAGE_TYPE_DESCRIPTION = "Message type"
MESSAGE_TYPE_CORRELATION = "Message ID for correlation"
MESSAGE_TYPE_TOOL_EXECUTE = "tool_execute"

CLOSE_CODE_INVALID_SESSION = 1008
CLOSE_CODE_SERVICE_UNAVAILABLE = 1011
CLOSE_CODE_INTERNAL_ERROR = 1011
