"""
Constants for search endpoints.
"""

MIN_LIMIT = 1
MAX_LIMIT = 100
DEFAULT_LIMIT = 20
DEFAULT_OFFSET = 0
VALID_MODES = {"semantic", "keyword", "hybrid"}

DEFAULT_SIMILARITY_THRESHOLD = 0.3
DEFAULT_SEMANTIC_WEIGHT = 0.6

MIN_CONTEXT_LIMIT = 1
MAX_CONTEXT_LIMIT = 20
DEFAULT_CONTEXT_LIMIT = 5
MIN_QUESTION_LENGTH = 3
