"""
Constants for provider endpoints.
"""

MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 2.0
DEFAULT_TEMPERATURE = 0.7

MIN_MAX_TOKENS = 1
MAX_MAX_TOKENS = 100000
DEFAULT_MAX_TOKENS = 2000

MIN_MESSAGE_LENGTH = 1
MIN_PROVIDER_ID_LENGTH = 1

MAX_SAMPLE_CONVERSATIONS = 5
