"""
Constants for settings endpoints.
"""

DEFAULT_TEMPERATURE = 0.7
MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 2.0

DEFAULT_MAX_OUTPUT_TOKENS = 2000
MIN_MAX_OUTPUT_TOKENS = 1
MAX_MAX_OUTPUT_TOKENS = 1000000

DEFAULT_RESPONSE_FORMAT = "concise"
VALID_RESPONSE_FORMATS = {"concise", "verbose"}

DEFAULT_CONTEXT_WINDOW_SIZE = 10
MIN_CONTEXT_WINDOW_SIZE = 1
MAX_CONTEXT_WINDOW_SIZE = 50

DEFAULT_RESPONSE_TIMEOUT = 30
MIN_RESPONSE_TIMEOUT = 5
MAX_RESPONSE_TIMEOUT = 300

DEFAULT_MAX_FILE_SIZE_MB = 100
MIN_MAX_FILE_SIZE_MB = 1
MAX_MAX_FILE_SIZE_MB = 1000

DEFAULT_SEARCH_RESULTS_LIMIT = 25
MIN_SEARCH_RESULTS_LIMIT = 1
MAX_SEARCH_RESULTS_LIMIT = 1000

DEFAULT_THEME = "dark"
VALID_THEMES = {"light", "dark", "system"}

DEFAULT_INTERFACE_DENSITY = "comfortable"
VALID_INTERFACE_DENSITIES = {"compact", "comfortable", "spacious"}

DEFAULT_IMPORT_LOCATION = "~/Documents"
