"""
Constants for conversation endpoints.
"""

MIN_LIMIT = 1
MAX_LIMIT = 500
DEFAULT_LIMIT = 50
DEFAULT_OFFSET = 0

MIN_MESSAGE_LIMIT = 1
MAX_MESSAGE_LIMIT = 500
DEFAULT_MESSAGE_LIMIT = 50

MIN_CONTEXT_LIMIT = 1
MAX_CONTEXT_LIMIT = 20
DEFAULT_CONTEXT_LIMIT = 5

MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 2.0
DEFAULT_TEMPERATURE = 0.7

MIN_MAX_TOKENS = 1
MAX_MAX_TOKENS = 100000
DEFAULT_MAX_TOKENS = 2000

DEFAULT_RESPONSE_TIMEOUT = 30
