"""
Classification rules package.
"""

from .primary_rules import (
    PRIMARY_DEFINITIVE_PHRASE_DEFINITIONS,
    PRIMARY_UNIQUE_PATTERN_DEFINITIONS,
)
from .secondary_rules import SECONDARY_STRUCTURE_PATTERN_DEFINITIONS
from .tertiary_rules import (
    TERTIARY_FILENAME_KEYWORD_DEFINITIONS,
    TERTIARY_STATISTICAL_KEYWORD_DEFINITIONS,
)

__all__ = [
    "PRIMARY_DEFINITIVE_PHRASE_DEFINITIONS",
    "PRIMARY_UNIQUE_PATTERN_DEFINITIONS",
    "SECONDARY_STRUCTURE_PATTERN_DEFINITIONS",
    "TERTIARY_STATISTICAL_KEYWORD_DEFINITIONS",
    "TERTIARY_FILENAME_KEYWORD_DEFINITIONS",
]
