TERTIARY_FILENAME_KEYWORD_DEFINITIONS = {
    "Financial": {
        "keywords": [
            "statement",
            "invoice",
            "receipt",
            "tax",
            "w2",
            "1099",
            "1040",
            "bill",
        ],
        "confidence": 0.75,
    },
    "Healthcare": {
        "keywords": [
            "medical",
            "prescription",
            "lab",
            "xray",
            "mri",
            "eob",
            "health",
        ],
        "confidence": 0.75,
    },
    "Legal": {
        "keywords": [
            "contract",
            "agreement",
            "lease",
            "will",
            "power_of_attorney",
            "legal",
        ],
        "confidence": 0.75,
    },
    "Professional": {
        "keywords": [
            "resume",
            "cv",
            "transcript",
            "certificate",
            "diploma",
            "recommendation",
        ],
        "confidence": 0.75,
    },
}


TERTIARY_STATISTICAL_KEYWORD_DEFINITIONS = {
    "Financial": {
        "account",
        "balance",
        "payment",
        "transaction",
        "deposit",
        "withdrawal",
        "interest",
        "fee",
        "charge",
        "credit",
        "debit",
        "investment",
        "portfolio",
        "dividend",
        "tax",
        "income",
        "expense",
        "budget",
        "invoice",
        "receipt",
        "statement",
    },
    "Healthcare": {
        "patient",
        "doctor",
        "physician",
        "diagnosis",
        "treatment",
        "medication",
        "prescription",
        "hospital",
        "clinic",
        "insurance",
        "procedure",
        "examination",
        "symptoms",
        "medical",
        "health",
        "disease",
        "condition",
        "therapy",
        "surgery",
        "recovery",
    },
    "Legal": {
        "agreement",
        "contract",
        "party",
        "clause",
        "term",
        "condition",
        "liability",
        "indemnity",
        "warranty",
        "dispute",
        "arbitration",
        "court",
        "judge",
        "attorney",
        "legal",
        "law",
        "rights",
        "obligation",
        "breach",
        "enforcement",
        "jurisdiction",
    },
    "Professional": {
        "experience",
        "education",
        "qualification",
        "skill",
        "employment",
        "position",
        "responsibility",
        "achievement",
        "reference",
        "degree",
        "certification",
        "training",
        "career",
        "resume",
        "objective",
        "accomplishment",
        "expertise",
        "proficiency",
        "competency",
    },
}
