"""
Constants for document endpoints.
"""

DOC_NEIGHBORS_LABEL = "Get document neighbors"

MIN_LIMIT = 1
MAX_LIMIT = 10000
DEFAULT_LIMIT = 20
DEFAULT_OFFSET = 0

COUNT_QUERY_LIMIT = 10000
DEDUPLICATION_CHECK_LIMIT = 100

MIN_NEIGHBORS = 1
MAX_NEIGHBORS = 100
DEFAULT_NEIGHBORS = 10

MIN_CHUNKS_LIMIT = 1
MAX_CHUNKS_LIMIT = 1000
DEFAULT_CHUNKS_LIMIT = 20
