name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  linting:
    name: "Code Linting"
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  documentation:
    name: "Documentation"
    uses: ./.github/workflows/docs.yml
    secrets: inherit

  unit-tests:
    name: "Unit Tests"
    needs: [linting, documentation]
    uses: ./.github/workflows/test-unit.yml
    secrets: inherit

  sonarcloud:
    name: "SonarCloud Analysis"
    if: always()
    needs: [unit-tests]
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit
    with:
      unit-coverage-artifact: "unit-tests-coverage"
